POST http://localhost:3000/songs HTTP/1.1
Content-Type: application/json

{
  "title": "Yeezy",
  "artist": ["Kanye"],
  "album": "New Album",
  "year": "2023",
  "releaseDate": "2023-10-01",
  "duration": "03:34"
}
###
GET http://localhost:3000/songs
###
GET http://localhost:3000/songs/1